package com.lottery.entity;

public class User {
}



// User's ticket
// Random verficiation number
// confimration number

// {
// id, firstname, lastname, personalcode, lotteryConfirmationCode.
//
// }

// /ticket -> POST request
// {
//
//    firstname
//    lastname
//    personal_code
//    email
//
// }

/*
*   confirmation number generated by rand
*   confirmation number is saved with user.
*   two db row is created - > user and lottery
*   after saving return the confirmation number
*   US - DV Lottery -
*   Lottery price/amount
*
*
* */