server:
  port: 9090
spring:
  profiles:
    active: dev

  application:
    name: e-lottery
  r2dbc:
    url: r2dbc:postgresql://localhost:4040/lottery_db
    username: test
    password: test

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:4040/lottery_db
    user: test
    password: test
    driver-class-name: org.postgresql.Driver

#  jdbc:postgresql://localhost:5432/mydb

#    liquibase:
#      enabled: true
#      change-log: classpath:/db/changelog/db.changelog-master.xml
#      url: r2dbc:postgresql://localhost:5432/your_database_name
#      username: your_database_username
#      password: your_database_password
#      driver-class-name:
#        driver: org.postgresql.Driver